<#
.SYNOPSIS
    Slides App + Decks — bundle installer (slides).

.DESCRIPTION
    Installs the slides Vite app, the source decks (spec-slides/), and the pre-built dist/ so index.html opens directly in the browser — no Node/build step required.

    MODE DISPATCH (spec §3 — chosen at startup, never switched mid-run)

      PINNED MODE
        Triggered by:  -Version <tag>   OR   -UseLocalArchive <path>
        Behavior:      Install EXACTLY that tag/archive. Refuses every
                       fallback in spec §4.2 (no /releases/latest, no
                       main branch, no V→V+N cross-repo jumps).
                       404 → exit 3.

      IMPLICIT MODE
        Triggered by:  no -Version and no -UseLocalArchive.
        Behavior:      Download the main-branch zip from codeload.
                       No git, no probes, no API calls.

    SOURCE-SELECTION FLAGS  (which mode each one forces)
      -Version <tag>          [→ PINNED]   Install this exact tag.
      -UseLocalArchive <path> [→ PINNED]   Extract a pre-staged .zip
                                           from disk. Implies -Offline.
                                           Overrides -Version.

    TARGET / OUTPUT FLAGS  (any mode)
      -Target <dir>     Install destination (default: cwd).
      -NoOpen           Skip auto-opening the entry file.

    NETWORK FLAGS
      -Offline          [any mode]   Refuse all network access. Use only
                                     with -UseLocalArchive, else fails
                                     with exit 2.

    MODE-SPECIFIC GUARDS  (no-op outside their stated mode)
      -NoMainFallback   [PINNED]    If a pinned release-asset 404s,
                                    refuse the tag-zip / main fallback.
                                    Exit 3.
                        [IMPLICIT]  Refuse the main-branch fallback.
                                    Exit 1 if no release is resolvable.
      -NoDiscovery      [IMPLICIT]  Forbid V→V+N cross-repo discovery
                                    (forward-compatible; not yet inlined
                                    here — see rollout plan).
                        [PINNED]    No-op (discovery is already forbidden
                                    by spec §4.2 / §6.4).

    EXIT CODES (spec §8)
      0  success
      1  generic failure (missing tool, unknown flag, implicit mode with
         -NoMainFallback when no release is resolvable)
      2  -Offline required a network operation
      3  pinned tag / asset not found (PINNED MODE)
      4  verification failed (required artifacts missing after extraction)
      5  inner installer / handoff rejected

    SPEC: spec/14-update/27-generic-installer-behavior.md

    After install, opens slides-app/dist/index.html in your default browser
    (suppress with -NoOpen).

    Pre-built artifact: slides-app/dist ships compiled inside the
    release archive. No build step required on the user machine.

    Folder mapping (src in repo → dest under target):
      spec-slides → spec-slides
      slides-app → slides-app

    Generated by scripts/generate-bundle-installers.mjs from bundles.json.
    Do not edit by hand — re-run `npm run bundles:generate` after
    editing the manifest.

.EXAMPLE
    irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v20/main/slides-install.ps1 | iex

.EXAMPLE
    & ([scriptblock]::Create((irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v20/main/slides-install.ps1))) -Version v5.8.0 -Target .\vendor
#>

param(
    [string]$Version = "",
    [string]$Target = "",
    [switch]$NoOpen,
    [switch]$Offline,
    [string]$UseLocalArchive = "",
    [switch]$NoDiscovery,
    [switch]$NoMainFallback,
    [switch]$RunFixRepo,
    [Alias("y","AssumeYes")]
    [switch]$Yes,
    [string]$LogDir = "",
    [switch]$ShowFixRepoLog,
    [int]$MaxFixRepoLogs = -1,
    [Alias("?")]
    [switch]$Help
)

# Env-var equivalent: INSTALL_RUN_FIX_REPO=1 enables -RunFixRepo without
# requiring callers to thread the flag through wrapper scripts.
if (-not $RunFixRepo) {
    $envFlag = $env:INSTALL_RUN_FIX_REPO
    if ($envFlag -and @("1","true","TRUE","yes","YES") -contains $envFlag) { $RunFixRepo = $true }
}
if (-not $Yes) {
    $envYes = $env:INSTALL_FIX_REPO_YES
    if ($envYes -and @("1","true","TRUE","yes","YES") -contains $envYes) { $Yes = $true }
}
if (-not $LogDir) { $LogDir = $env:INSTALL_LOG_DIR }
if (-not $LogDir) { $LogDir = "" }
if (-not $ShowFixRepoLog) {
    $envShow = $env:INSTALL_SHOW_FIX_REPO_LOG
    if ($envShow -and @("1","true","TRUE","yes","YES") -contains $envShow) { $ShowFixRepoLog = $true }
}
if ($MaxFixRepoLogs -lt 0) {
    $envMax = $env:INSTALL_MAX_FIX_REPO_LOGS
    if ($envMax -and ($envMax -match '^\d+$')) { $MaxFixRepoLogs = [int]$envMax } else { $MaxFixRepoLogs = 0 }
}

# ── -Help / -? short-circuit (spec §B.1.c.i) ──────────────────────
# Surfaces the comment-based help block above without requiring the user
# to know about Get-Help. Print to stdout and exit 0 BEFORE any side
# effects (no folder creation, no banner, no download).
if ($Help) {
    try { Get-Help $PSCommandPath -Full } catch { Write-Host (Get-Content -LiteralPath $PSCommandPath -ErrorAction SilentlyContinue | Select-Object -First 100) }
    return
}

# ── Crash-safe execution wrapper (iex-friendly) ───────────────────
# The script is commonly invoked as:  irm <url> | iex
# In that mode the script body runs INSIDE the caller's PowerShell
# session, so any `exit <n>` would terminate the host terminal and
# any uncaught exception would surface as a red wall of text with
# no log trail. We:
#   1. Save the caller's $ErrorActionPreference and restore it on exit.
#   2. Route every fatal condition through Stop-Install, which writes
#      a crash log under $env:TEMP\installer-logs\ and
#      throws a tagged exception we can swallow at the outer catch.
#   3. Wrap the entire main body in a single try/catch that prints a
#      friendly summary + log path and `return`s without killing the
#      host (no `exit` calls reach the caller's session).
$Script:__PriorErrorActionPreference = $ErrorActionPreference
$Script:__PriorProgressPreference    = $ProgressPreference
$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"

$Script:__InstallCrashLogDir = Join-Path ([System.IO.Path]::GetTempPath()) "installer-logs"
try { New-Item -ItemType Directory -Path $Script:__InstallCrashLogDir -Force | Out-Null } catch { }
$Script:__InstallCrashLogFile = Join-Path $Script:__InstallCrashLogDir ("slides-install-" + (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ") + ".log")

function Write-InstallLog {
    param([string]$Line)
    try { Add-Content -LiteralPath $Script:__InstallCrashLogFile -Value $Line -ErrorAction SilentlyContinue } catch { }
}

# Header always written so the log is useful even on early failures.
Write-InstallLog "# slides-install crash log"
Write-InstallLog ("# started: " + (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ"))
Write-InstallLog ("# pwsh:    " + $PSVersionTable.PSEdition + " " + $PSVersionTable.PSVersion)
Write-InstallLog ("# os:      " + [System.Runtime.InteropServices.RuntimeInformation]::OSDescription)
Write-InstallLog ("# cwd:     " + (Get-Location).Path)
Write-InstallLog "# ────────────────────────────────────────────────"

function Restore-CallerPreferences {
    if ($null -ne $Script:__PriorErrorActionPreference) { $ErrorActionPreference = $Script:__PriorErrorActionPreference }
    if ($null -ne $Script:__PriorProgressPreference)    { $ProgressPreference    = $Script:__PriorProgressPreference }
}

function Stop-Install {
    param([int]$Code = 1, [string]$Message = "")
    Write-InstallLog ("[stop-install] code=" + $Code + " message=" + $Message)
    if ($Message) { Write-Host $Message -ForegroundColor Red }
    # Tagged exception so the outer catch can format a single, friendly tail.
    throw [System.Management.Automation.RuntimeException]::new("__INSTALL_STOP__|$Code|$Message")
}


$BundleName = "slides"
$BundleMapping = "spec-slides|spec-slides,slides-app|slides-app"
$ArchiveStableName = "slides"
$ReleaseBase = "https://github.com/alimtvnetwork/coding-guidelines-v20/releases"
$RepoSlug = "alimtvnetwork/coding-guidelines-v20"
$AutoOpenEntry = "slides-app/dist/index.html"
$PrebuiltSrc = "slides-app/dist"
$PrebuiltDest = "slides-app/dist"
$VerifyPairs = "slides-app/dist/index.html|file,spec-slides|dir"

if ($UseLocalArchive) { $Offline = $true }

if ([string]::IsNullOrEmpty($Target)) { $Target = (Get-Location).Path }
New-Item -ItemType Directory -Path $Target -Force | Out-Null
$Target = (Resolve-Path $Target).Path

# ── Mode dispatch (spec §3) ───────────────────────────────────────
if ($UseLocalArchive) {
    $Mode = "pinned"
    $Source = "local-archive"
    $TarballUrl = "(none — local archive)"
    $VersionLabel = "(local archive: $UseLocalArchive)"
} elseif ($Version) {
    $Mode = "pinned"
    $Source = "release-asset"
    $TarballUrl = "$ReleaseBase/download/$Version/$ArchiveStableName.zip"
    $VersionLabel = $Version
} else {
    $Mode = "implicit"
    $Source = "main-branch"
    $TarballUrl = "https://codeload.github.com/$RepoSlug/zip/refs/heads/main"
    $VersionLabel = "main"
}

Write-Host ""
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
# Spec §7 banner — literal field names: mode/repo/version/source.
Write-Host "  📦 slides-install v5.8.0" -ForegroundColor Cyan
Write-Host "     mode:    $Mode" -ForegroundColor Cyan
Write-Host "     repo:    $RepoSlug" -ForegroundColor Cyan
Write-Host "     version: $VersionLabel" -ForegroundColor Cyan
Write-Host "     source:  $Source" -ForegroundColor Cyan
Write-Host "  ────────────────────────────────────────────────────" -ForegroundColor Cyan
Write-Host "  Target: $Target" -ForegroundColor Cyan
Write-Host "  URL:    $TarballUrl" -ForegroundColor Cyan
Write-Host "  Folder mapping (src in archive → dest under target):" -ForegroundColor Cyan
foreach ($pair in $BundleMapping.Split(",")) {
    $parts = $pair.Split("|")
    Write-Host "    • $($parts[0]) → $(Join-Path $Target $parts[1])" -ForegroundColor Cyan
}
if ($PrebuiltSrc) {
    Write-Host "  Prebuilt: $PrebuiltSrc → $(Join-Path $Target $PrebuiltDest) (compiled, no build step)" -ForegroundColor Cyan
}
if ($AutoOpenEntry) {
    if ($NoOpen) {
        Write-Host "  AutoOpen: $(Join-Path $Target $AutoOpenEntry) (disabled by -NoOpen)" -ForegroundColor Cyan
    } else {
        Write-Host "  AutoOpen: $(Join-Path $Target $AutoOpenEntry) (suppress with -NoOpen)" -ForegroundColor Cyan
    }
}
if ($Offline) {
    Write-Host "  Net:    OFFLINE (no downloads will be attempted)" -ForegroundColor Yellow
}
if ($NoDiscovery) {
    Write-Host "  Discovery: DISABLED (-NoDiscovery: V→V+N cross-repo probe forbidden)" -ForegroundColor Yellow
}
if ($NoMainFallback) {
    Write-Host "  MainFallback: DISABLED (-NoMainFallback: implicit mode will not fall back to main)" -ForegroundColor Yellow
}
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

function Get-MappingPairs {
    return $BundleMapping.Split(",") | ForEach-Object {
        $parts = $_.Split("|")
        [pscustomobject]@{ Src = $parts[0]; Dest = $parts[1] }
    }
}

function Resolve-ArchiveRoot {
    param([string]$ExtractDir)
    # Codeload zips wrap content in <repo>-<ref>/ — descend if needed.
    $first = Get-ChildItem -Path $ExtractDir -Directory | Select-Object -First 1
    if ($first) {
        $probe = (Get-MappingPairs)[0].Src
        if (-not (Test-Path (Join-Path $ExtractDir $probe)) -and
             (Test-Path (Join-Path $first.FullName $probe))) {
            return $first.FullName
        }
    }
    return $ExtractDir
}

function Copy-Mapping {
    param([string]$ExtractDir)
    $root = Resolve-ArchiveRoot -ExtractDir $ExtractDir
    foreach ($pair in (Get-MappingPairs)) {
        $srcPath = Join-Path $root $pair.Src
        if (-not (Test-Path $srcPath)) {
            Write-Warning "  archive missing $($pair.Src) — skipping"
            continue
        }
        $destPath = Join-Path $Target $pair.Dest
        New-Item -ItemType Directory -Path $destPath -Force | Out-Null
        Copy-Item -Path (Join-Path $srcPath '*') -Destination $destPath -Recurse -Force
        Write-Host "  ✓ $($pair.Src) → $destPath" -ForegroundColor Green
    }
}

function Open-Entry {
    if (-not $AutoOpenEntry) { return }
    $entryPath = Join-Path $Target $AutoOpenEntry
    # Always surface the exact path so the user can copy/paste it even if
    # auto-open succeeds or silently no-ops (RDP, headless, locked browser).
    Write-Host ""
    Write-Host "  📄 Entry file: $entryPath" -ForegroundColor Cyan
    Write-Host "  🔗 file:///$($entryPath -replace '\\','/')" -ForegroundColor Cyan
    if (-not (Test-Path $entryPath)) {
        Write-Warning "  ⚠️  entry file does NOT exist on disk — skipping auto-open"
        Write-Warning "     (the install completed but the prebuilt artifact appears missing)"
        return
    }
    if ($NoOpen) {
        Write-Host "  ℹ️  -NoOpen set — not launching browser. Open the path above manually."
        return
    }
    Write-Host "  ▸ opening $entryPath"
    try {
        if ($IsWindows -or $env:OS -eq "Windows_NT") {
            if (Get-Command Start-Process -ErrorAction SilentlyContinue) {
                Start-Process $entryPath
            } else {
                Write-Warning "  ❌ 'Start-Process' not available in this PowerShell host."
                Write-Warning "     Open the path above manually in your browser."
            }
        } elseif ($IsMacOS) {
            if (Get-Command open -ErrorAction SilentlyContinue) {
                & open $entryPath
            } else {
                Write-Warning "  ❌ 'open' command not found on macOS (this is unexpected)."
                Write-Warning "     Open the path above manually in your browser."
            }
        } elseif ($IsLinux) {
            if (Get-Command xdg-open -ErrorAction SilentlyContinue) {
                & xdg-open $entryPath
            } else {
                Write-Warning "  ❌ 'xdg-open' not installed — cannot auto-launch browser."
                Write-Warning "     Install with one of:"
                Write-Warning "       Debian/Ubuntu : sudo apt-get install xdg-utils"
                Write-Warning "       Fedora/RHEL   : sudo dnf install xdg-utils"
                Write-Warning "       Arch          : sudo pacman -S xdg-utils"
                Write-Warning "     Or open the path above manually in your browser."
            }
        } else {
            Write-Warning "  ❌ Unknown OS — cannot auto-launch browser."
            Write-Warning "     Open the path above manually in your browser."
        }
    } catch {
        Write-Warning "  ⚠️  auto-open threw an error: $($_.Exception.Message)"
        Write-Warning "     Open the path above manually in your browser."
    }
}

function Install-ViaArchive {
    $archiveUrl = "$ReleaseBase/download/$Version/$ArchiveStableName.zip"
    if ($Offline) {
        Stop-Install -Code 2 -Message "❌ -Offline set but versioned archive requires network download.`n   URL: $archiveUrl`n   Re-run without -Offline, or pre-stage the archive locally."
    }
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $zipPath = Join-Path $tmp "bundle.zip"
        Write-Host "  ▸ downloading $archiveUrl"
        try {
            Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        } catch {
            if ($NoMainFallback) {
                Stop-Install -Code 3 -Message "❌ release archive not found for $Version and -NoMainFallback set.`n   URL: $archiveUrl`n   Refusing to fall back to the main-branch zip. ($($_.Exception.Message))"
            }
            Write-Warning "  release archive not found for $Version — falling back to main branch: $($_.Exception.Message)"
            Install-ViaMainBranch
            return
        }
        $extractDir = Join-Path $tmp "extract"
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Install-ViaMainBranch {
    $archiveUrl = "https://codeload.github.com/$RepoSlug/zip/refs/heads/main"
    if ($Offline) {
        Stop-Install -Code 2 -Message "❌ -Offline set but main-branch zip is required.`n   URL: $archiveUrl`n   Re-run without -Offline (network access needed to fetch the bundle)."
    }
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $zipPath = Join-Path $tmp "repo.zip"
        Write-Host "  ▸ downloading $archiveUrl"
        Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        $extractDir = Join-Path $tmp "extract"
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Install-ViaLocalArchive {
    # -UseLocalArchive PATH: extract a pre-staged .zip from disk.
    # Skips ALL network access. The path must exist and end in .zip;
    # for .tar.gz / .tgz pre-staged archives use the Bash installer
    # (--use-local-archive) — Expand-Archive only handles zip.
    if (-not (Test-Path -LiteralPath $UseLocalArchive -PathType Leaf)) {
        Stop-Install -Code 1 -Message "❌ -UseLocalArchive: file not found: $UseLocalArchive`n   Provide an absolute or relative path to a .zip file."
    }
    if ($UseLocalArchive -notmatch '\.zip$') {
        Stop-Install -Code 1 -Message "❌ -UseLocalArchive: expected .zip, got: $UseLocalArchive`n   The PowerShell installer extracts zip archives only. For .tar.gz`n   archives use the Bash installer (--use-local-archive)."
    }
    $absArchive = (Resolve-Path -LiteralPath $UseLocalArchive).Path
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $extractDir = Join-Path $tmp "extract"
        Write-Host "  ▸ extracting local archive: $absArchive"
        try {
            Expand-Archive -LiteralPath $absArchive -DestinationPath $extractDir -Force
        } catch {
            Stop-Install -Code 1 -Message "❌ failed to extract local archive: $absArchive`n   The file is not a valid zip, or it is corrupt. ($($_.Exception.Message))"
        }
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

try {

if ($UseLocalArchive) {
    Install-ViaLocalArchive
} elseif ($Version) {
    Install-ViaArchive
} else {
    if ($NoMainFallback) {
        Stop-Install -Code 1 -Message "❌ implicit mode (no -Version) requires the main-branch zip, but -NoMainFallback was set.`n   Re-run with -Version <tag>, -UseLocalArchive <path>, or omit -NoMainFallback."
    }
    Install-ViaMainBranch
}


Write-Host ""
function Verify-Install {
    if (-not $VerifyPairs) { return }
    $missing = @()
    foreach ($pair in $VerifyPairs.Split(",")) {
        $parts = $pair.Split("|")
        $relpath = $parts[0]
        $kind = $parts[1]
        $absPath = Join-Path $Target $relpath
        switch ($kind) {
            "file" { if (-not (Test-Path -LiteralPath $absPath -PathType Leaf))      { $missing += "file: $absPath" } }
            "dir"  { if (-not (Test-Path -LiteralPath $absPath -PathType Container)) { $missing += "dir : $absPath" } }
            default { Write-Warning "  unknown verify kind '$kind' for $relpath — skipping" }
        }
    }
    if ($missing.Count -gt 0) {
        Write-Host ""
        Write-Host "❌ Install verification FAILED — $($missing.Count) required path(s) missing:" -ForegroundColor Red
        foreach ($m in $missing) { Write-Host "     • $m" -ForegroundColor Red }
        Write-Host ""
        Write-Host "   The archive was downloaded and extracted but did NOT contain"
        Write-Host "   the expected artifacts. Common causes:"
        Write-Host "     • A pinned -Version was published before the prebuilt artifact"
        Write-Host "       was added to the release. Try re-running without -Version"
        Write-Host "       to fetch the main-branch zip."
        Write-Host "     • The release workflow failed to build the prebuilt artifact."
        Write-Host "     • A previous -Target run partially overwrote the install."
        Stop-Install -Code 4 -Message ""
    }
    $count = $VerifyPairs.Split(",").Count
    Write-Host "  ✓ verified $count required path(s) present" -ForegroundColor Green
}
Verify-Install

function Invoke-FixRepo {
    # Auto-execute the freshly installed fix-repo.ps1 so the repo is
    # patched in the same invocation. Streams stdout+stderr to a
    # timestamped log under <Target>/.install-logs/. Failures
    # propagate as exit 5 (spec §8: "inner installer / handoff rejected").
    $script = Join-Path $Target "fix-repo.ps1"
    if (-not (Test-Path -LiteralPath $script -PathType Leaf)) {
        Write-Host "❌ -RunFixRepo: $script not found after install." -ForegroundColor Red
        Stop-Install -Code 5 -Message ""
    }
    if ($Yes) {
        Write-Host "  ▸ auto-confirmed (-Yes / INSTALL_FIX_REPO_YES=1)" -ForegroundColor DarkGray
    } elseif ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected) {
        Write-Host ""
        Write-Host "⚠️  About to run $script" -ForegroundColor Yellow
        Write-Host "   This will rewrite versioned-repo-name tokens across tracked text files." -ForegroundColor Yellow
        $reply = Read-Host "Proceed? [y/N]"
        if ($reply -notmatch '^(y|Y|yes|YES)$') {
            Write-Host "fix-repo skipped by user — exiting with code 5." -ForegroundColor Yellow
            Stop-Install -Code 5 -Message ""
        }
    } else {
        Write-Host "❌ -RunFixRepo requires confirmation but session is non-interactive." -ForegroundColor Red
        Write-Host "   Re-run with -Yes (or INSTALL_FIX_REPO_YES=1) to bypass the prompt." -ForegroundColor Red
        Stop-Install -Code 5 -Message ""
    }
    if ($LogDir) {
        if ([System.IO.Path]::IsPathRooted($LogDir)) { $logDir = $LogDir }
        else { $logDir = Join-Path $Target $LogDir }
    } else {
        $logDir = Join-Path $Target ".install-logs"
    }
    if (-not (Test-Path -LiteralPath $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyyMMddTHHmmssZ")
    $logFile = Join-Path $logDir "fix-repo-$ts.log"
    @(
        "# fix-repo log",
        "# started:  $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))",
        "# script:   $script",
        "# target:   $Target",
        "# os:       $([System.Runtime.InteropServices.RuntimeInformation]::OSDescription)",
        "# shell:    PowerShell $($PSVersionTable.PSEdition) $($PSVersionTable.PSVersion)",
        "# uname:    $([System.Runtime.InteropServices.RuntimeInformation]::OSDescription) / $([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)",
        "# cwd:      $((Get-Location).Path)",
        "# ──────────────────────────────────────────────────────────"
    ) | Set-Content -LiteralPath $logFile -Encoding UTF8
    Write-Host ""
    Write-Host "  ▸ running fix-repo: $script" -ForegroundColor Cyan
    Write-Host "  ▸ log: $logFile" -ForegroundColor Cyan
    & $script 2>&1 | Tee-Object -FilePath $logFile -Append
    $rc = $LASTEXITCODE
    Add-Content -LiteralPath $logFile -Value "# exit: $rc  finished: $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
    if ($MaxFixRepoLogs -lt 0) {
        Write-Host "  ▸ log pruning: SKIPPED (--max-fix-repo-logs=$MaxFixRepoLogs is not a non-negative integer)" -ForegroundColor Yellow
    } elseif ($MaxFixRepoLogs -eq 0) {
        Write-Host "  ▸ log pruning: DISABLED (--max-fix-repo-logs=0)" -ForegroundColor Cyan
    } else {
        $allLogs = @(Get-ChildItem -LiteralPath $logDir -Filter 'fix-repo-*.log' -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending)
        $stale = $allLogs | Select-Object -Skip $MaxFixRepoLogs
        $removedCount = 0
        foreach ($s in $stale) { Remove-Item -LiteralPath $s.FullName -Force -ErrorAction SilentlyContinue; $removedCount++ }
        $kept = $allLogs.Count - $removedCount
        Write-Host "  ▸ log pruning: --max-fix-repo-logs=$MaxFixRepoLogs | found=$($allLogs.Count) kept=$kept pruned=$removedCount dir=$logDir" -ForegroundColor Cyan
    }
    if ($ShowFixRepoLog) {
        Write-Host ""
        Write-Host "─── fix-repo log: $logFile ─────────────────────────────"
        Get-Content -LiteralPath $logFile | ForEach-Object { Write-Host $_ }
        Write-Host "─── end of log ──────────────────────────────────────────"
    }
    if ($rc -ne 0) {
        Write-Host "❌ fix-repo.ps1 failed (exit $rc) — see $logFile" -ForegroundColor Red
        Stop-Install -Code 5 -Message ""
    }
    Write-Host "  ✓ fix-repo completed (log: $logFile)" -ForegroundColor Green
}

if ($RunFixRepo) { Invoke-FixRepo }

Write-Host "✅ $BundleName installed." -ForegroundColor Green
Open-Entry
Write-InstallLog "[ok] install completed cleanly"
Restore-CallerPreferences

} catch {
    # Single, friendly tail for ANY failure path. Never `exit` — that
    # would terminate the host PowerShell when the script is invoked
    # via `irm <url> | iex`. Instead we log, print, restore prefs,
    # and `return` from the script scope.
    $err = $_
    $msg = $err.Exception.Message
    $code = 1
    if ($msg -match '^__INSTALL_STOP__\|(\d+)\|(.*)$') {
        $code = [int]$Matches[1]
        $msg  = $Matches[2]
    }
    Write-Host ""
    Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Red
    Write-Host "  ❌ slides-install failed (code $code)" -ForegroundColor Red
    if ($msg) { Write-Host "     $msg" -ForegroundColor Red }
    Write-Host "  ────────────────────────────────────────────────────" -ForegroundColor Red
    Write-Host "  Crash log: $Script:__InstallCrashLogFile" -ForegroundColor Yellow
    Write-Host "  Stack trace (also written to log):" -ForegroundColor DarkGray
    Write-Host ("     " + $err.ScriptStackTrace) -ForegroundColor DarkGray
    Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Red
    Write-InstallLog ("[crash] code=" + $code + " message=" + $msg)
    Write-InstallLog ("[crash] " + ($err | Out-String))
    Restore-CallerPreferences
    # Set $LASTEXITCODE so callers that inspect it still see the failure,
    # but DO NOT call `exit` — that would close the user's terminal
    # when running via `irm | iex`.
    $global:LASTEXITCODE = $code
    return
}

