<#
.SYNOPSIS
    Split-DB Architecture Spec — bundle installer (splitdb).

.DESCRIPTION
    Installs the database conventions, split-DB architecture, and seedable config specs.

    MODE DISPATCH (spec §3 — chosen at startup, never switched mid-run)

      PINNED MODE
        Triggered by:  -Version <tag>   OR   -UseLocalArchive <path>
        Behavior:      Install EXACTLY that tag/archive. Refuses every
                       fallback in spec §4.2 (no /releases/latest, no
                       main branch, no V→V+N cross-repo jumps).
                       404 → exit 3.

      IMPLICIT MODE
        Triggered by:  no -Version and no -UseLocalArchive.
        Behavior:      Download the main-branch zip from codeload.
                       No git, no probes, no API calls.

    SOURCE-SELECTION FLAGS  (which mode each one forces)
      -Version <tag>          [→ PINNED]   Install this exact tag.
      -UseLocalArchive <path> [→ PINNED]   Extract a pre-staged .zip
                                           from disk. Implies -Offline.
                                           Overrides -Version.

    TARGET / OUTPUT FLAGS  (any mode)
      -Target <dir>     Install destination (default: cwd).
      -NoOpen           Skip auto-opening the entry file.

    NETWORK FLAGS
      -Offline          [any mode]   Refuse all network access. Use only
                                     with -UseLocalArchive, else fails
                                     with exit 2.

    MODE-SPECIFIC GUARDS  (no-op outside their stated mode)
      -NoMainFallback   [PINNED]    If a pinned release-asset 404s,
                                    refuse the tag-zip / main fallback.
                                    Exit 3.
                        [IMPLICIT]  Refuse the main-branch fallback.
                                    Exit 1 if no release is resolvable.
      -NoDiscovery      [IMPLICIT]  Forbid V→V+N cross-repo discovery
                                    (forward-compatible; not yet inlined
                                    here — see rollout plan).
                        [PINNED]    No-op (discovery is already forbidden
                                    by spec §4.2 / §6.4).

    EXIT CODES (spec §8)
      0  success
      1  generic failure (missing tool, unknown flag, implicit mode with
         -NoMainFallback when no release is resolvable)
      2  -Offline required a network operation
      3  pinned tag / asset not found (PINNED MODE)
      4  verification failed (required artifacts missing after extraction)
      5  inner installer / handoff rejected

    SPEC: spec/14-update/27-generic-installer-behavior.md

    Folder mapping (src in repo → dest under target):
      spec/04-database-conventions → spec/04-database-conventions
      spec/05-split-db-architecture → spec/05-split-db-architecture
      spec/06-seedable-config-architecture → spec/06-seedable-config-architecture

    Generated by scripts/generate-bundle-installers.mjs from bundles.json.
    Do not edit by hand — re-run `npm run bundles:generate` after
    editing the manifest.

.EXAMPLE
    irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v18/main/splitdb-install.ps1 | iex

.EXAMPLE
    & ([scriptblock]::Create((irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v18/main/splitdb-install.ps1))) -Version v4.7.0 -Target .\vendor
#>

param(
    [string]$Version = "",
    [string]$Target = "",
    [switch]$NoOpen,
    [switch]$Offline,
    [string]$UseLocalArchive = "",
    [switch]$NoDiscovery,
    [switch]$NoMainFallback,
    [Alias("?")]
    [switch]$Help
)

# ── -Help / -? short-circuit (spec §B.1.c.i) ──────────────────────
# Surfaces the comment-based help block above without requiring the user
# to know about Get-Help. Print to stdout and exit 0 BEFORE any side
# effects (no folder creation, no banner, no download).
if ($Help) {
    Get-Help $PSCommandPath -Full
    exit 0
}

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$BundleName = "splitdb"
$BundleMapping = "spec/04-database-conventions|spec/04-database-conventions,spec/05-split-db-architecture|spec/05-split-db-architecture,spec/06-seedable-config-architecture|spec/06-seedable-config-architecture"
$ArchiveStableName = "splitdb"
$ReleaseBase = "https://github.com/alimtvnetwork/coding-guidelines-v18/releases"
$RepoSlug = "alimtvnetwork/coding-guidelines-v18"
$AutoOpenEntry = ""
$PrebuiltSrc = ""
$PrebuiltDest = ""
$VerifyPairs = ""

if ($UseLocalArchive) { $Offline = $true }

if ([string]::IsNullOrEmpty($Target)) { $Target = (Get-Location).Path }
New-Item -ItemType Directory -Path $Target -Force | Out-Null
$Target = (Resolve-Path $Target).Path

# ── Mode dispatch (spec §3) ───────────────────────────────────────
if ($UseLocalArchive) {
    $Mode = "pinned"
    $Source = "local-archive"
    $TarballUrl = "(none — local archive)"
    $VersionLabel = "(local archive: $UseLocalArchive)"
} elseif ($Version) {
    $Mode = "pinned"
    $Source = "release-asset"
    $TarballUrl = "$ReleaseBase/download/$Version/$ArchiveStableName.zip"
    $VersionLabel = $Version
} else {
    $Mode = "implicit"
    $Source = "main-branch"
    $TarballUrl = "https://codeload.github.com/$RepoSlug/zip/refs/heads/main"
    $VersionLabel = "main"
}

Write-Host ""
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
# Spec §7 banner — literal field names: mode/repo/version/source.
Write-Host "  📦 splitdb-install v4.7.0" -ForegroundColor Cyan
Write-Host "     mode:    $Mode" -ForegroundColor Cyan
Write-Host "     repo:    $RepoSlug" -ForegroundColor Cyan
Write-Host "     version: $VersionLabel" -ForegroundColor Cyan
Write-Host "     source:  $Source" -ForegroundColor Cyan
Write-Host "  ────────────────────────────────────────────────────" -ForegroundColor Cyan
Write-Host "  Target: $Target" -ForegroundColor Cyan
Write-Host "  URL:    $TarballUrl" -ForegroundColor Cyan
Write-Host "  Folder mapping (src in archive → dest under target):" -ForegroundColor Cyan
foreach ($pair in $BundleMapping.Split(",")) {
    $parts = $pair.Split("|")
    Write-Host "    • $($parts[0]) → $(Join-Path $Target $parts[1])" -ForegroundColor Cyan
}
if ($PrebuiltSrc) {
    Write-Host "  Prebuilt: $PrebuiltSrc → $(Join-Path $Target $PrebuiltDest) (compiled, no build step)" -ForegroundColor Cyan
}
if ($AutoOpenEntry) {
    if ($NoOpen) {
        Write-Host "  AutoOpen: $(Join-Path $Target $AutoOpenEntry) (disabled by -NoOpen)" -ForegroundColor Cyan
    } else {
        Write-Host "  AutoOpen: $(Join-Path $Target $AutoOpenEntry) (suppress with -NoOpen)" -ForegroundColor Cyan
    }
}
if ($Offline) {
    Write-Host "  Net:    OFFLINE (no downloads will be attempted)" -ForegroundColor Yellow
}
if ($NoDiscovery) {
    Write-Host "  Discovery: DISABLED (-NoDiscovery: V→V+N cross-repo probe forbidden)" -ForegroundColor Yellow
}
if ($NoMainFallback) {
    Write-Host "  MainFallback: DISABLED (-NoMainFallback: implicit mode will not fall back to main)" -ForegroundColor Yellow
}
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

function Get-MappingPairs {
    return $BundleMapping.Split(",") | ForEach-Object {
        $parts = $_.Split("|")
        [pscustomobject]@{ Src = $parts[0]; Dest = $parts[1] }
    }
}

function Resolve-ArchiveRoot {
    param([string]$ExtractDir)
    # Codeload zips wrap content in <repo>-<ref>/ — descend if needed.
    $first = Get-ChildItem -Path $ExtractDir -Directory | Select-Object -First 1
    if ($first) {
        $probe = (Get-MappingPairs)[0].Src
        if (-not (Test-Path (Join-Path $ExtractDir $probe)) -and
             (Test-Path (Join-Path $first.FullName $probe))) {
            return $first.FullName
        }
    }
    return $ExtractDir
}

function Copy-Mapping {
    param([string]$ExtractDir)
    $root = Resolve-ArchiveRoot -ExtractDir $ExtractDir
    foreach ($pair in (Get-MappingPairs)) {
        $srcPath = Join-Path $root $pair.Src
        if (-not (Test-Path $srcPath)) {
            Write-Warning "  archive missing $($pair.Src) — skipping"
            continue
        }
        $destPath = Join-Path $Target $pair.Dest
        New-Item -ItemType Directory -Path $destPath -Force | Out-Null
        Copy-Item -Path (Join-Path $srcPath '*') -Destination $destPath -Recurse -Force
        Write-Host "  ✓ $($pair.Src) → $destPath" -ForegroundColor Green
    }
}

function Open-Entry {
    if (-not $AutoOpenEntry) { return }
    $entryPath = Join-Path $Target $AutoOpenEntry
    # Always surface the exact path so the user can copy/paste it even if
    # auto-open succeeds or silently no-ops (RDP, headless, locked browser).
    Write-Host ""
    Write-Host "  📄 Entry file: $entryPath" -ForegroundColor Cyan
    Write-Host "  🔗 file:///$($entryPath -replace '\\','/')" -ForegroundColor Cyan
    if (-not (Test-Path $entryPath)) {
        Write-Warning "  ⚠️  entry file does NOT exist on disk — skipping auto-open"
        Write-Warning "     (the install completed but the prebuilt artifact appears missing)"
        return
    }
    if ($NoOpen) {
        Write-Host "  ℹ️  -NoOpen set — not launching browser. Open the path above manually."
        return
    }
    Write-Host "  ▸ opening $entryPath"
    try {
        if ($IsWindows -or $env:OS -eq "Windows_NT") {
            if (Get-Command Start-Process -ErrorAction SilentlyContinue) {
                Start-Process $entryPath
            } else {
                Write-Warning "  ❌ 'Start-Process' not available in this PowerShell host."
                Write-Warning "     Open the path above manually in your browser."
            }
        } elseif ($IsMacOS) {
            if (Get-Command open -ErrorAction SilentlyContinue) {
                & open $entryPath
            } else {
                Write-Warning "  ❌ 'open' command not found on macOS (this is unexpected)."
                Write-Warning "     Open the path above manually in your browser."
            }
        } elseif ($IsLinux) {
            if (Get-Command xdg-open -ErrorAction SilentlyContinue) {
                & xdg-open $entryPath
            } else {
                Write-Warning "  ❌ 'xdg-open' not installed — cannot auto-launch browser."
                Write-Warning "     Install with one of:"
                Write-Warning "       Debian/Ubuntu : sudo apt-get install xdg-utils"
                Write-Warning "       Fedora/RHEL   : sudo dnf install xdg-utils"
                Write-Warning "       Arch          : sudo pacman -S xdg-utils"
                Write-Warning "     Or open the path above manually in your browser."
            }
        } else {
            Write-Warning "  ❌ Unknown OS — cannot auto-launch browser."
            Write-Warning "     Open the path above manually in your browser."
        }
    } catch {
        Write-Warning "  ⚠️  auto-open threw an error: $($_.Exception.Message)"
        Write-Warning "     Open the path above manually in your browser."
    }
}

function Install-ViaArchive {
    $archiveUrl = "$ReleaseBase/download/$Version/$ArchiveStableName.zip"
    if ($Offline) {
        Write-Error "❌ -Offline set but versioned archive requires network download.`n   URL: $archiveUrl`n   Re-run without -Offline, or pre-stage the archive locally."
        exit 2
    }
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $zipPath = Join-Path $tmp "bundle.zip"
        Write-Host "  ▸ downloading $archiveUrl"
        try {
            Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        } catch {
            if ($NoMainFallback) {
                Write-Error "❌ release archive not found for $Version and -NoMainFallback set.`n   URL: $archiveUrl`n   Refusing to fall back to the main-branch zip. ($($_.Exception.Message))"
                exit 3
            }
            Write-Warning "  release archive not found for $Version — falling back to main branch: $($_.Exception.Message)"
            Install-ViaMainBranch
            return
        }
        $extractDir = Join-Path $tmp "extract"
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Install-ViaMainBranch {
    $archiveUrl = "https://codeload.github.com/$RepoSlug/zip/refs/heads/main"
    if ($Offline) {
        Write-Error "❌ -Offline set but main-branch zip is required.`n   URL: $archiveUrl`n   Re-run without -Offline (network access needed to fetch the bundle)."
        exit 2
    }
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $zipPath = Join-Path $tmp "repo.zip"
        Write-Host "  ▸ downloading $archiveUrl"
        Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        $extractDir = Join-Path $tmp "extract"
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Install-ViaLocalArchive {
    # -UseLocalArchive PATH: extract a pre-staged .zip from disk.
    # Skips ALL network access. The path must exist and end in .zip;
    # for .tar.gz / .tgz pre-staged archives use the Bash installer
    # (--use-local-archive) — Expand-Archive only handles zip.
    if (-not (Test-Path -LiteralPath $UseLocalArchive -PathType Leaf)) {
        Write-Error "❌ -UseLocalArchive: file not found: $UseLocalArchive`n   Provide an absolute or relative path to a .zip file."
        exit 1
    }
    if ($UseLocalArchive -notmatch '\.zip$') {
        Write-Error "❌ -UseLocalArchive: expected .zip, got: $UseLocalArchive`n   The PowerShell installer extracts zip archives only. For .tar.gz`n   archives use the Bash installer (--use-local-archive)."
        exit 1
    }
    $absArchive = (Resolve-Path -LiteralPath $UseLocalArchive).Path
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $extractDir = Join-Path $tmp "extract"
        Write-Host "  ▸ extracting local archive: $absArchive"
        try {
            Expand-Archive -LiteralPath $absArchive -DestinationPath $extractDir -Force
        } catch {
            Write-Error "❌ failed to extract local archive: $absArchive`n   The file is not a valid zip, or it is corrupt. ($($_.Exception.Message))"
            exit 1
        }
        Copy-Mapping -ExtractDir $extractDir
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

if ($UseLocalArchive) {
    Install-ViaLocalArchive
} elseif ($Version) {
    Install-ViaArchive
} else {
    if ($NoMainFallback) {
        Write-Error "❌ implicit mode (no -Version) requires the main-branch zip, but -NoMainFallback was set.`n   Re-run with -Version <tag>, -UseLocalArchive <path>, or omit -NoMainFallback."
        exit 1
    }
    Install-ViaMainBranch
}

Write-Host ""
function Verify-Install {
    if (-not $VerifyPairs) { return }
    $missing = @()
    foreach ($pair in $VerifyPairs.Split(",")) {
        $parts = $pair.Split("|")
        $relpath = $parts[0]
        $kind = $parts[1]
        $absPath = Join-Path $Target $relpath
        switch ($kind) {
            "file" { if (-not (Test-Path -LiteralPath $absPath -PathType Leaf))      { $missing += "file: $absPath" } }
            "dir"  { if (-not (Test-Path -LiteralPath $absPath -PathType Container)) { $missing += "dir : $absPath" } }
            default { Write-Warning "  unknown verify kind '$kind' for $relpath — skipping" }
        }
    }
    if ($missing.Count -gt 0) {
        Write-Host ""
        Write-Host "❌ Install verification FAILED — $($missing.Count) required path(s) missing:" -ForegroundColor Red
        foreach ($m in $missing) { Write-Host "     • $m" -ForegroundColor Red }
        Write-Host ""
        Write-Host "   The archive was downloaded and extracted but did NOT contain"
        Write-Host "   the expected artifacts. Common causes:"
        Write-Host "     • A pinned -Version was published before the prebuilt artifact"
        Write-Host "       was added to the release. Try re-running without -Version"
        Write-Host "       to fetch the main-branch zip."
        Write-Host "     • The release workflow failed to build the prebuilt artifact."
        Write-Host "     • A previous -Target run partially overwrote the install."
        exit 4
    }
    $count = $VerifyPairs.Split(",").Count
    Write-Host "  ✓ verified $count required path(s) present" -ForegroundColor Green
}
Verify-Install
Write-Host "✅ $BundleName installed." -ForegroundColor Green
Open-Entry
