#!/usr/bin/env bash
# =====================================================================
# splitdb-install.sh — Split-DB Architecture Spec
#
# Installs the database conventions, split-DB architecture, and seedable config specs.
#
# Mode dispatch (spec §3 — chosen at startup, never switched mid-run):
#   PINNED   = --version <tag> OR --use-local-archive <path>
#              → install EXACTLY that tag/archive. No fallback. No
#                discovery. 404 → exit 3.
#   IMPLICIT = no --version, no --use-local-archive
#              → fetch the main-branch tarball (codeload.github.com).
#                Works behind firewalls; no git, no /releases/latest probe.
#
# Run with -h or --help for the full flag reference (scope-tagged).
#
# Spec: spec/14-update/27-generic-installer-behavior.md §3, §7, §8.
#
#
# Folder mapping (src in repo → dest under target):
#   spec/04-database-conventions → spec/04-database-conventions
#   spec/05-split-db-architecture → spec/05-split-db-architecture
#   spec/06-seedable-config-architecture → spec/06-seedable-config-architecture
#
# Generated by scripts/generate-bundle-installers.mjs from bundles.json.
# Do not edit by hand — re-run `npm run bundles:generate` after
# editing the manifest.
# =====================================================================

set -euo pipefail

BUNDLE_NAME="splitdb"
BUNDLE_MAPPING="spec/04-database-conventions|spec/04-database-conventions spec/05-split-db-architecture|spec/05-split-db-architecture spec/06-seedable-config-architecture|spec/06-seedable-config-architecture"
ARCHIVE_STABLE_NAME="splitdb"
RELEASE_BASE="https://github.com/alimtvnetwork/coding-guidelines-v16/releases"
REPO_SLUG="alimtvnetwork/coding-guidelines-v16"
AUTO_OPEN_ENTRY=""
PREBUILT_SRC=""
PREBUILT_DEST=""
VERIFY_PAIRS=""

VERSION=""
TARGET="$(pwd)"
DO_OPEN=true
OFFLINE=false
LOCAL_ARCHIVE=""
NO_DISCOVERY=false
NO_MAIN_FALLBACK=false

usage() {
  cat <<HELP
splitdb-install.sh — Split-DB Architecture Spec

USAGE
  splitdb-install.sh [FLAGS]

MODE DISPATCH (spec §3 — exactly one mode is chosen at startup)
  PINNED MODE
    Triggered by:  --version <tag>   OR   --use-local-archive <path>
    Behavior:      Install EXACTLY that tag/archive. Refuses every
                   fallback in spec §4.2 (no /releases/latest, no main
                   branch, no V→V+N cross-repo jumps). 404 → exit 3.

  IMPLICIT MODE
    Triggered by:  no --version and no --use-local-archive.
    Behavior:      Download the main-branch tarball directly from
                   codeload.github.com. No git, no probes, no API calls.
                   (V→V+N parallel discovery is forward-compatible —
                   see --no-discovery below.)

SOURCE-SELECTION FLAGS (which mode each one forces)
  --version <tag>             [→ PINNED]   Install this exact tag.
  --use-local-archive <path>  [→ PINNED]   Extract a pre-staged
                                           .tar.gz from disk. Implies
                                           --offline. Overrides --version.

TARGET / OUTPUT FLAGS (any mode)
  --target <dir>, --dest <dir>   Install destination (default: cwd).
  --no-open                      Skip auto-opening the entry file.

NETWORK FLAGS
  --offline                   [any mode]   Refuse all network access.
                                           Use only with --use-local-archive,
                                           else fails with exit 2.

MODE-SPECIFIC GUARDS (no-op outside their stated mode)
  --no-main-fallback          [PINNED]    If a pinned release-asset 404s,
                                          refuse to fall back to the
                                          tag-tarball or main. Exit 3.
                              [IMPLICIT]  Refuse the main-branch fallback
                                          entirely. Exit 1 if no release.
  --no-discovery              [IMPLICIT]  Forbid V→V+N cross-repo
                                          discovery (forward-compatible:
                                          discovery isn't yet inlined in
                                          this installer; see rollout
                                          plan).
                              [PINNED]    No-op (discovery is already
                                          forbidden by spec §4.2 / §6.4).

OTHER
  -h, --help                  Show this help and exit.

EXIT CODES (spec §8)
  0  success
  1  generic failure (missing tool, unknown flag, implicit mode with
     --no-main-fallback when no release is resolvable)
  2  --offline required a network operation
  3  pinned tag / asset not found (PINNED MODE)
  4  verification failed (required artifacts missing after extraction)
  5  inner installer / handoff rejected

SPEC
  spec/14-update/27-generic-installer-behavior.md
HELP
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)        VERSION="$2"; shift 2 ;;
    --target|--dest)  TARGET="$2";  shift 2 ;;
    --no-open)        DO_OPEN=false; shift ;;
    --offline)        OFFLINE=true; shift ;;
    --no-discovery)   NO_DISCOVERY=true; shift ;;
    --no-main-fallback) NO_MAIN_FALLBACK=true; shift ;;
    --use-local-archive)
      LOCAL_ARCHIVE="$2"; OFFLINE=true; shift 2 ;;
    -h|--help)        usage; exit 0 ;;
    *) echo "❌ Unknown option: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "${TARGET}"
TARGET="$(cd "${TARGET}" && pwd)"

# ── Mode dispatch (spec §3) ───────────────────────────────────────
# PINNED  = strict version supplied (CLI flag, env, baked-in, or URL).
# IMPLICIT = no strict version → discovery / main-branch fallback.
# Local-archive is a sub-mode that operates without network access; it
# is classified as PINNED-by-disk because the user explicitly chose the
# exact bytes on disk.
if [[ -n "${LOCAL_ARCHIVE}" ]]; then
  MODE="pinned"
  SOURCE="local-archive"
  TARBALL_URL="(none — local archive)"
elif [[ -n "${VERSION}" ]]; then
  MODE="pinned"
  SOURCE="release-asset"
  TARBALL_URL="${RELEASE_BASE}/download/${VERSION}/${ARCHIVE_STABLE_NAME}.tar.gz"
else
  MODE="implicit"
  SOURCE="main-branch"
  TARBALL_URL="https://codeload.github.com/${REPO_SLUG}/tar.gz/refs/heads/main"
fi

echo ""
# Spec §7 banner — literal field names: mode/repo/version/source.
echo "════════════════════════════════════════════════════════"
echo "  📦 splitdb-install v3.77.0"
echo "     mode:    ${MODE}"
echo "     repo:    ${REPO_SLUG}"
if [[ -n "${LOCAL_ARCHIVE}" ]]; then
  echo "     version: (local archive: ${LOCAL_ARCHIVE})"
elif [[ -n "${VERSION}" ]]; then
  echo "     version: ${VERSION}"
else
  echo "     version: main"
fi
echo "     source:  ${SOURCE}"
echo "  ────────────────────────────────────────────────────"
echo "  Target: ${TARGET}"
echo "  URL:    ${TARBALL_URL}"
echo "  ────────────────────────────────────────────────────"
echo "  Folder mapping (src in archive → dest under target):"
for pair in ${BUNDLE_MAPPING}; do
  src="${pair%|*}"
  dest="${pair#*|}"
  echo "    • ${src} → ${TARGET}/${dest}"
done
if [[ -n "${PREBUILT_SRC}" ]]; then
  echo "  Prebuilt: ${PREBUILT_SRC} → ${TARGET}/${PREBUILT_DEST} (compiled, no build step)"
fi
if [[ -n "${AUTO_OPEN_ENTRY}" ]]; then
  if ${DO_OPEN}; then
    echo "  AutoOpen: ${TARGET}/${AUTO_OPEN_ENTRY} (suppress with --no-open)"
  else
    echo "  AutoOpen: ${TARGET}/${AUTO_OPEN_ENTRY} (disabled by --no-open)"
  fi
fi
if ${OFFLINE}; then
  echo "  Net:    OFFLINE (no downloads will be attempted)"
fi
if ${NO_DISCOVERY}; then
  echo "  Discovery: DISABLED (--no-discovery: V→V+N cross-repo probe forbidden)"
fi
if ${NO_MAIN_FALLBACK}; then
  echo "  MainFallback: DISABLED (--no-main-fallback: implicit mode will not fall back to main)"
fi
echo "════════════════════════════════════════════════════════"
echo ""

# ── Helpers ───────────────────────────────────────────────────────
have() { command -v "$1" >/dev/null 2>&1; }

download() {
  # download URL OUT  → 0 success, 1 failure
  local url="$1" out="$2"
  if have curl; then
    curl -fsSL --retry 2 --retry-delay 1 -o "${out}" "${url}" && return 0 || return 1
  elif have wget; then
    wget -qO "${out}" "${url}" && return 0 || return 1
  else
    echo "❌ Neither curl nor wget found. Install one and retry." >&2
    exit 1
  fi
}

extract_mapping() {
  # extract mapping from extract_root → TARGET, honoring src|dest pairs.
  # When src is missing inside the archive, look one level deeper
  # (codeload tarballs wrap content in <repo>-<ref>/).
  local extract_root="$1"
  local archive_root="${extract_root}"
  if [[ -d "${extract_root}" ]]; then
    local first_child
    first_child="$(find "${extract_root}" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
    if [[ -n "${first_child}" ]]; then
      # Heuristic: if none of the mapping srcs exist at root but DO exist
      # inside first_child, treat first_child as the archive root.
      local probe="${BUNDLE_MAPPING%% *}"
      local probe_src="${probe%|*}"
      if [[ ! -d "${extract_root}/${probe_src}" && -d "${first_child}/${probe_src}" ]]; then
        archive_root="${first_child}"
      fi
    fi
  fi

  local pair src dest
  for pair in ${BUNDLE_MAPPING}; do
    src="${pair%|*}"
    dest="${pair#*|}"
    if [[ ! -d "${archive_root}/${src}" ]]; then
      echo "  ⚠️  archive missing ${src} — skipping" >&2
      continue
    fi
    mkdir -p "${TARGET}/${dest}"
    cp -R "${archive_root}/${src}/." "${TARGET}/${dest}/"
    echo "  ✓ ${src} → ${TARGET}/${dest}"
  done
}

open_entry() {
  [[ -z "${AUTO_OPEN_ENTRY}" ]] && return 0
  local entry_path="${TARGET}/${AUTO_OPEN_ENTRY}"
  # Always surface the exact path so the user can copy/paste it even if
  # auto-open succeeds (some browsers steal focus, some headless shells
  # silently no-op).
  echo ""
  echo "  📄 Entry file: ${entry_path}"
  echo "  🔗 file://${entry_path}"
  if [[ ! -f "${entry_path}" ]]; then
    echo "  ⚠️  entry file does NOT exist on disk — skipping auto-open" >&2
    echo "     (the install completed but the prebuilt artifact appears missing)" >&2
    return 0
  fi
  if ! ${DO_OPEN}; then
    echo "  ℹ️  --no-open set — not launching browser. Open the path above manually."
    return 0
  fi
  echo "  ▸ opening ${entry_path}"
  local os; os="$(uname -s 2>/dev/null || echo unknown)"
  case "${os}" in
    Darwin*)
      if have open; then
        open "${entry_path}" >/dev/null 2>&1 || \
          echo "  ⚠️  'open' returned an error — open the path above manually." >&2
      else
        echo "  ❌ 'open' command not found on macOS (this is unexpected)." >&2
        echo "     Open the path above manually in your browser." >&2
      fi
      ;;
    Linux*)
      if have xdg-open; then
        xdg-open "${entry_path}" >/dev/null 2>&1 &
      else
        echo "  ❌ 'xdg-open' not installed — cannot auto-launch browser." >&2
        echo "     Install with one of:" >&2
        echo "       Debian/Ubuntu : sudo apt-get install xdg-utils" >&2
        echo "       Fedora/RHEL   : sudo dnf install xdg-utils" >&2
        echo "       Arch          : sudo pacman -S xdg-utils" >&2
        echo "     Or open the path above manually in your browser." >&2
      fi
      ;;
    MINGW*|MSYS*|CYGWIN*)
      if have start; then
        start "" "${entry_path}" >/dev/null 2>&1 || \
          echo "  ⚠️  'start' returned an error — open the path above manually." >&2
      else
        echo "  ❌ 'start' command not found in this shell." >&2
        echo "     Open the path above manually in your browser." >&2
      fi
      ;;
    *)
      echo "  ❌ Unknown OS '${os}' — cannot auto-launch browser." >&2
      echo "     Open the path above manually in your browser." >&2
      ;;
  esac
}

verify_install() {
  # Iterate VERIFY_PAIRS ("relpath|kind ..."). On any miss, print the full
  # list of missing probes and exit 4 (spec §8: verification failed).
  # NB exit 3 is reserved for "pinned tag/asset not found" — distinct
  # from "tag downloaded but contents missing required paths".
  # successful unless every probe passes.
  [[ -z "${VERIFY_PAIRS}" ]] && return 0
  local pair relpath kind abs_path missing=()
  for pair in ${VERIFY_PAIRS}; do
    relpath="${pair%|*}"
    kind="${pair#*|}"
    abs_path="${TARGET}/${relpath}"
    case "${kind}" in
      file)
        [[ -f "${abs_path}" ]] || missing+=("file: ${abs_path}")
        ;;
      dir)
        [[ -d "${abs_path}" ]] || missing+=("dir : ${abs_path}")
        ;;
      *)
        echo "  ⚠️  unknown verify kind '${kind}' for ${relpath} — skipping" >&2
        ;;
    esac
  done
  if [[ ${#missing[@]} -gt 0 ]]; then
    echo "" >&2
    echo "❌ Install verification FAILED — ${#missing[@]} required path(s) missing:" >&2
    local m
    for m in "${missing[@]}"; do
      echo "     • ${m}" >&2
    done
    echo "" >&2
    echo "   The archive was downloaded and extracted but did NOT contain" >&2
    echo "   the expected artifacts. Common causes:" >&2
    echo "     • A pinned --version was published before the prebuilt artifact" >&2
    echo "       was added to the release. Try re-running without --version" >&2
    echo "       to fetch the main-branch tarball." >&2
    echo "     • The release workflow failed to build the prebuilt artifact." >&2
    echo "     • A previous --target run partially overwrote the install." >&2
    exit 4
  fi
  echo "  ✓ verified $(echo "${VERIFY_PAIRS}" | wc -w | tr -d ' ') required path(s) present"
}

install_via_archive() {
  local archive_url="${RELEASE_BASE}/download/${VERSION}/${ARCHIVE_STABLE_NAME}.tar.gz"
  if ${OFFLINE}; then
    echo "❌ --offline set but versioned archive requires network download." >&2
    echo "   URL: ${archive_url}" >&2
    echo "   Re-run without --offline, or pre-stage the archive locally." >&2
    exit 2
  fi
  local tmp; tmp="$(mktemp -d)"
  trap 'rm -rf "'"${tmp}"'"' EXIT

  echo "  ▸ downloading ${archive_url}"
  if ! download "${archive_url}" "${tmp}/bundle.tar.gz"; then
    if ${NO_MAIN_FALLBACK}; then
      echo "❌ release archive not found for ${VERSION} and --no-main-fallback set." >&2
      echo "   URL: ${archive_url}" >&2
      echo "   Refusing to fall back to the main-branch tarball." >&2
      exit 3
    fi
    echo "  ⚠️  release archive not found for ${VERSION} — falling back to main branch" >&2
    install_via_main_branch
    return
  fi
  mkdir -p "${tmp}/extract"
  tar -xzf "${tmp}/bundle.tar.gz" -C "${tmp}/extract"
  extract_mapping "${tmp}/extract"
}

install_via_main_branch() {
  local archive_url="https://codeload.github.com/${REPO_SLUG}/tar.gz/refs/heads/main"
  if ${OFFLINE}; then
    echo "❌ --offline set but main-branch tarball is required." >&2
    echo "   URL: ${archive_url}" >&2
    echo "   Re-run without --offline (network access needed to fetch the bundle)." >&2
    exit 2
  fi
  local tmp; tmp="$(mktemp -d)"
  trap 'rm -rf "'"${tmp}"'"' EXIT

  echo "  ▸ downloading ${archive_url}"
  if ! download "${archive_url}" "${tmp}/repo.tar.gz"; then
    echo "❌ failed to download main-branch tarball from ${archive_url}" >&2
    exit 1
  fi
  mkdir -p "${tmp}/extract"
  tar -xzf "${tmp}/repo.tar.gz" -C "${tmp}/extract"
  extract_mapping "${tmp}/extract"
}

install_via_local_archive() {
  # --use-local-archive PATH: extract a pre-staged .tar.gz from disk.
  # Skips ALL network access. The path must exist, be readable, and look
  # like a gzipped tar (we accept .tar.gz, .tgz; anything else is
  # rejected with a clear error so users do not silently mis-stage a zip).
  if [[ ! -f "${LOCAL_ARCHIVE}" ]]; then
    echo "❌ --use-local-archive: file not found: ${LOCAL_ARCHIVE}" >&2
    echo "   Provide an absolute or relative path to a .tar.gz / .tgz file." >&2
    exit 1
  fi
  if [[ ! -r "${LOCAL_ARCHIVE}" ]]; then
    echo "❌ --use-local-archive: file not readable: ${LOCAL_ARCHIVE}" >&2
    exit 1
  fi
  case "${LOCAL_ARCHIVE}" in
    *.tar.gz|*.tgz) : ;;
    *)
      echo "❌ --use-local-archive: expected .tar.gz or .tgz, got: ${LOCAL_ARCHIVE}" >&2
      echo "   The Bash installer extracts gzipped tarballs only. For .zip" >&2
      echo "   archives use the PowerShell installer (-UseLocalArchive)." >&2
      exit 1
      ;;
  esac
  local abs_archive
  abs_archive="$(cd "$(dirname "${LOCAL_ARCHIVE}")" && pwd)/$(basename "${LOCAL_ARCHIVE}")"
  local tmp; tmp="$(mktemp -d)"
  trap 'rm -rf "'"${tmp}"'"' EXIT
  echo "  ▸ extracting local archive: ${abs_archive}"
  mkdir -p "${tmp}/extract"
  if ! tar -xzf "${abs_archive}" -C "${tmp}/extract"; then
    echo "❌ failed to extract local archive: ${abs_archive}" >&2
    echo "   The file is not a valid gzipped tarball, or it is corrupt." >&2
    exit 1
  fi
  extract_mapping "${tmp}/extract"
}

if [[ -n "${LOCAL_ARCHIVE}" ]]; then
  install_via_local_archive
elif [[ -n "${VERSION}" ]]; then
  install_via_archive
else
  if ${NO_MAIN_FALLBACK}; then
    echo "❌ implicit mode (no --version) requires the main-branch tarball, but --no-main-fallback was set." >&2
    echo "   Re-run with --version <tag>, --use-local-archive <path>, or omit --no-main-fallback." >&2
    exit 1
  fi
  install_via_main_branch
fi

echo ""
verify_install
echo "✅ ${BUNDLE_NAME} installed."
open_entry
